apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    name: db-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 800Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/mysql
    type: DirectoryOrCreate