apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: db-pod
spec:
  ports:
  - port: 3306
    name: db-port
  clusterIP: None
  selector:
    app: db-pod  #pod label




# kubectl create secret generic db-secret \
# --from-literal=root-password="secure-root-pw" \
# --from-literal=auth-password="my-secret-pw" \
# --from-literal=secret-key="xco0sr0fh4e52x03g9mv"


# kubectl get secret db-secret