---
kind: Service
apiVersion: v1
metadata:
  name:  api-svc
spec:
  selector:
    app: api-pod
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: http
    protocol: TCP


# kubectl create secret generic api-secret \
# --from-literal=apikey=42222be920mshdb9a0d4573c19dbp10837ajsne5d9608fbbc3


# curl --request GET \
# 	--url https://open-weather13.p.rapidapi.com/city/landon/EN \
# 	--header 'x-rapidapi-host: open-weather13.p.rapidapi.com' \
# 	--header 'x-rapidapi-key: 42222be920mshdb9a0d4573c19dbp10837ajsne5d9608fbbc3'