---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod 
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
      - name: auth-pod
        image: afakharany/weatherapp-auth:lab
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            value: db-svc
          - name: DB_USER
            value: authuser
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: auth-password
          - name: DB_NAME
            value: weatherapp
          - name: DB_PORT
            value: "3306"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: secret-key